-- ─────────────────────────────────────────────────────────────────
-- Migration 057: Schedule foundation, drafts, carry-forward, race-fix
-- ─────────────────────────────────────────────────────────────────
-- Run in Supabase Dashboard → SQL Editor (single block is fine).
-- After running: Settings → API → Reload Schema Cache.
--
-- This migration is the foundation for the new invoicing model:
--   • Each fee_group becomes (class × term)-scoped — one schedule per term.
--   • Invoices gain 'draft' and 'carried_forward' statuses.
--   • Invoices track carry-forward source + amount (audit trail).
--   • Invoices track issued_at and last_printed_at.
--   • A unique constraint kills the duplicate-invoice race condition.
--
-- This migration is SAFE to re-run (uses IF NOT EXISTS / IF EXISTS).
-- It does NOT delete or rewrite any existing data.
-- ─────────────────────────────────────────────────────────────────


-- ════════════════════════════════════════════════════════════════
-- 1. fee_groups: add term_id (each schedule belongs to one term)
-- ════════════════════════════════════════════════════════════════
ALTER TABLE fee_groups
    ADD COLUMN IF NOT EXISTS term_id UUID REFERENCES terms(id) ON DELETE RESTRICT;

COMMENT ON COLUMN fee_groups.term_id IS
    'Each fee schedule belongs to one term. NULL on legacy rows from before migration 057.';

CREATE INDEX IF NOT EXISTS idx_fee_groups_term
    ON fee_groups (term_id);

-- One schedule per (class, term). Partial index lets legacy NULLs coexist.
CREATE UNIQUE INDEX IF NOT EXISTS idx_fee_groups_unique_class_term
    ON fee_groups (school_id, class_id, term_id)
    WHERE class_id IS NOT NULL AND term_id IS NOT NULL;


-- ════════════════════════════════════════════════════════════════
-- 2. invoices.status: allow 'draft' and 'carried_forward'
-- ════════════════════════════════════════════════════════════════
-- The original status CHECK constraint name is auto-generated by Postgres.
-- We find and drop it (whatever name it has), then re-add with new values.
DO $$
DECLARE
    cname TEXT;
BEGIN
    FOR cname IN
        SELECT conname FROM pg_constraint
        WHERE conrelid = 'public.invoices'::regclass
          AND contype = 'c'
          AND pg_get_constraintdef(oid) ILIKE '%status%'
          AND pg_get_constraintdef(oid) ILIKE '%unpaid%'
    LOOP
        EXECUTE format('ALTER TABLE invoices DROP CONSTRAINT %I', cname);
    END LOOP;
END $$;

ALTER TABLE invoices
    ADD CONSTRAINT invoices_status_check
    CHECK (status IN ('draft', 'unpaid', 'partial', 'paid', 'overdue', 'cancelled', 'carried_forward'));


-- ════════════════════════════════════════════════════════════════
-- 3. invoices: carry-forward, issued_at, last_printed_at
-- ════════════════════════════════════════════════════════════════
ALTER TABLE invoices
    ADD COLUMN IF NOT EXISTS carry_forward_source_id UUID REFERENCES invoices(id) ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS carry_forward_amount    NUMERIC(12,2) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS issued_at               TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS last_printed_at         TIMESTAMPTZ;

COMMENT ON COLUMN invoices.carry_forward_source_id IS
    'If this invoice rolled forward an unpaid balance, points to the previous-term invoice that was carried.';
COMMENT ON COLUMN invoices.carry_forward_amount IS
    'KSh amount carried forward from carry_forward_source_id (already included in invoices.amount).';
COMMENT ON COLUMN invoices.issued_at IS
    'When the invoice transitioned from draft → unpaid (i.e. became visible to parents).';
COMMENT ON COLUMN invoices.last_printed_at IS
    'Last time this invoice was included in a bulk-print run. Used to filter "not yet printed".';

CREATE INDEX IF NOT EXISTS idx_invoices_carry_forward_source
    ON invoices (carry_forward_source_id)
    WHERE carry_forward_source_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_invoices_status_term
    ON invoices (school_id, term_id, status);


-- ════════════════════════════════════════════════════════════════
-- 4. invoices: unique constraint to kill duplicate-invoice race
-- ════════════════════════════════════════════════════════════════
-- One invoice per (student, fee_group, term). Excludes cancelled
-- invoices so a regenerate-after-cancel is allowed.
CREATE UNIQUE INDEX IF NOT EXISTS idx_invoices_unique_per_term
    ON invoices (school_id, student_id, fee_group_id, term_id)
    WHERE fee_group_id IS NOT NULL AND status != 'cancelled';


-- ════════════════════════════════════════════════════════════════
-- 5. Backfill issued_at on existing non-draft invoices
-- ════════════════════════════════════════════════════════════════
-- Existing invoices are all "issued" by definition (they were
-- created by the old code which had no draft concept). Set their
-- issued_at to created_at so reports don't show NULLs.
UPDATE invoices
SET issued_at = created_at
WHERE issued_at IS NULL
  AND status IN ('unpaid', 'partial', 'paid', 'overdue');


-- ════════════════════════════════════════════════════════════════
-- Done. Verify with:
--
--   SELECT column_name, data_type
--   FROM information_schema.columns
--   WHERE table_name = 'invoices'
--     AND column_name IN ('carry_forward_source_id','carry_forward_amount','issued_at','last_printed_at');
--
--   SELECT indexname FROM pg_indexes
--   WHERE indexname IN ('idx_fee_groups_unique_class_term','idx_invoices_unique_per_term');
--
--   -- Test the new statuses are allowed (rolls back automatically):
--   BEGIN;
--   INSERT INTO invoices (school_id, student_id, amount, status, reference)
--   SELECT school_id, id, 1, 'draft', 'TEST-DRAFT' FROM students LIMIT 1;
--   ROLLBACK;
-- ════════════════════════════════════════════════════════════════
